FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Install curl for healthcheck
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY pom.xml .
RUN mvn dependency:go-offline -B


EXPOSE 8080

# Use spring-boot:run for hot reload
CMD ["mvn", "spring-boot:run"]